* Hydra-Ergo Some ergonomic shortcuts for common uses.
  :PROPERTIES:
  :ID:       3c84cb21-89c4-4784-a166-207419370f2e
  :END:
#+BEGIN_SRC emacs-lisp :results silent  
  (defhydra hydra-ergo (evil-normal-state-map "SPC" evil-motion-state-map :color blue)
  "hydra-ergo "
  ("a" execute-extended-command :color blue)
  ("d" hydra-ergo-d-menu/body :color blue)
  ("f" ivy-switch-buffer :color blue)
  ("i" hydra-ergo-i-menu/body :color blue)
  ("o" (lambda ()
	  (interactive)
	  (other-window 1)
	  (hydra-ergo-o-menu/body)) :color blue)
  ("r" hydra-ergo-r-menu/body :color blue)
  ("ö" save-buffer :color blue)
  ("w" ace-window :color blue)
  ("j" evil-search-forward :color blue)
  ("k" evil-search-backward :color blue)
  ("l" swiper :color blue)
  ("m" hydra-ergo-m-menu/body :color blue)
  ("s" hydra-ergo-s-menu/body :color blue)
  ("y" hydra-ergo-y-menu/body :color blue)
  ("c" hydra-ergo-c-menu/body :color blue)
  ("2" split-window-below :color blue)
  ("3" split-window-right :color blue)
  ("4" delete-other-windows :color blue)
  ("5" make-frame-command :color blue)
  ("0" delete-window :color blue)
  ("," fixup-whitespace :color blue))
  (global-set-key (kbd "M-SPC") 'hydra-ergo/body)
#+END_SRC
** c-menu
   :PROPERTIES:
   :ID:       70aa02bf-39b5-4abb-9fe1-aef8a6c0a1ab
   :END:
 I'm using c for org-mode so far. In xah-keys it's used for copy or selecting which evil-mode handles for me instead.
 #+BEGIN_SRC emacs-lisp :results silent
   (defhydra hydra-ergo-c-menu (:color blue)
     ("n" org-narrow-to-subtree)
     ("d" widen)
     ("i" hydra-ergo-org-download/body)
     ("j" (org-brain-visualize (org-brain-entry-at-pt)))
     ("x" (org-cut-special))
     ("w" (org-copy-special))
     ("y" (org-paste-special nil)))
 #+END_SRC
** d-menu_
   :PROPERTIES:
   :ID:       b9e34c0b-1b1a-4f90-a42e-a07994ddf827
   :END:
 I can't find the dired command in xah-fly-keys and since the "d" key is bound to things already 
 handled by vim I'll use d-menu as a dired-keymap
 #+BEGIN_SRC emacs-lisp :results silent 
   (defhydra hydra-ergo-d-menu (:color blue)
     ("f" dired)
     ("j" dired-jump)
     ("k" ranger))
 #+END_SRC
** e-menu
 Encapsulate e.g. (),{} etc
** i-menu 
   :PROPERTIES:
   :ID:       8b982e6c-4461-4a53-95ca-cf9d0ec9779d
   :END:
 #+BEGIN_SRC emacs-lisp :results silent
   (defhydra hydra-ergo-i-menu (:color blue)
	   "i-menu"
	   ("e" find-file)
	   ("o" bookmark-jump)
	   ("p" bookmark-set)
	   ("i" bookmark-bmenu-list))
 #+END_SRC
** m-menu
   :PROPERTIES:
   :ID:       7cab08df-e421-4331-b64b-6c0a50727245
   :END:
 Copied from the xah-fly-t-keymap. k-map for qwerty.
 Replace with buffer functions over time.
 #+BEGIN_SRC emacs-lisp :results silent 
   (defhydra hydra-ergo-m-menu (:color blue)
      ;; ("SPC" xah-clean-whitespace)
      ;; ("TAB" move-to-column)
      ;; ("1" xah-clear-register-1)
      ;; ("2" xah-append-to-register-1)
      ;; ("3" xah-copy-to-register-1)
      ;; ("4" xah-paste-from-register-1)
      ("." sort-lines)
      ("," sort-numeric-fields)
      ("'" reverse-region)
      ;; ("c" goto-char)
      ("d" mark-defun)
      ("e" list-matching-lines)
      ;; ("f" goto-line)
      ("i" delete-non-matching-lines)
      ("j" copy-to-register)
      ("l" insert-register)
      ("k" kill-buffer)
      ;; ("l" xah-escape-quotes)
      ;; ("m" xah-make-backup-and-save)
      ("n" repeat-complex-command)
      ("p" query-replace-regexp)
      ("r" revert-buffer)
      ("t" repeat)
      ("u" delete-matching-lines)
      ;; ("w" xah-next-window-or-frame)
      ("y" delete-duplicate-lines))
 #+END_SRC
** o-menu
   :PROPERTIES:
   :ID:       fd2e6082-b530-4572-9bac-74fa80fee2ac
   :END:
 #+BEGIN_SRC emacs-lisp :results silent
 (defhydra hydra-ergo-o-menu (:color red)
	 ("o" other-window :color red))
 #+END_SRC
** r-menu
   :PROPERTIES:
   :ID:       5f95bea7-bd96-4edc-b415-e87fad0d23fe
   :END:
   Register and logical operations.
   #+BEGIN_SRC emacs-lisp :results silent 
     (defhydra hydra-ergo-r-menu (:color blue)
       "r-menu"
       ("i" evil-numbers/inc-at-pt)
       ("d" evil-numbers/dec-at-pt))
   #+END_SRC
** s-menu
   :PROPERTIES:
   :ID:       257c02d8-e550-4c31-b796-5f5af560a03b
   :END:
   Format org text
   #+BEGIN_SRC emacs-lisp :results silent 
     (defhydra hydra-ergo-s-menu (:color blue)
       "Format Text org-mode-style"
       ("i" (ergo-surround #x2F))
       ("b" (ergo-surround #x2A))
       ("u" (ergo-surround #x5F))
       ("k" (ergo-surround #x2D)))
   #+END_SRC
** y-menu
   :PROPERTIES:
   :ID:       e2117bde-9f29-4a17-a6a3-a8bcb23ab7d5
   :END:
 #+BEGIN_SRC emacs-lisp :results silent 
   (defhydra hydra-ergo-y-menu (:color blue)
     ("d" aya-create)
     ("f" aya-expand))
 #+END_SRC
** Subhydras
*** org-download
    :PROPERTIES:
    :ID:       8c65b7bf-859e-403c-ace9-7b1b9ccff70c
    :END:
   #+BEGIN_SRC emacs-lisp :results silent
     (defhydra hydra-ergo-org-download (:color blue)
       ("i" org-download-screenshot)
       ("d" org-download-delete))
   #+END_SRC 
** Help Functions
   :PROPERTIES:
   :ID:       ce94237c-1725-4a67-aba4-b1ce691d16aa
   :END:
#+BEGIN_SRC emacs-lisp :results silent
  (defun ergo-surround (c)
      (interactive)
      (backward-char)
      (evil-forward-WORD-end)
      (forward-char)
      (insert-char c)
      (evil-backward-WORD-begin)
      (insert-char c)
      (evil-forward-WORD-end))
#+END_SRC
